### ISSUE TITLE
다른 이름으로 저장 클릭시 새로운 모달창 생성 & 해당 버튼 클릭시 관련 api 호출 함수 작성

### ISSUE THREAD

**Issue by ExceptAnyone** [ExceptAnyone/SSAP-IDE-FrontEnd#45]
## 작업 사항

> 

## To-do
- [ ] 다른 이름으로 저장 클릭 시 새로운 모달창 생성
- [ ] 해당 버튼 클릭시 관련 api 호출 함수 작성
- [ ] 새롭게 복제하는 기능

## 기타사항

> 기타 사항을 작성해주세요
